parameters:
    database_driver: pdo_sqlite
    database_host: null
    database_port: null
    database_name: pgqmanager
    database_user: null
    database_password: null
    database_path: /tmp/pgqmanager.db
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ueGexQL5l7ypR9R08etUHRa3qIinPuEkJlz