parameters:
#    config.example.class: PgqManager\ConfigBundle\Example

services:
#    config.example:
#        class: %config.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
      kernel.listener.config_route:
          class: PgqManager\ConfigBundle\Listener\ConfigRouteListener
          tags:
              - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
          arguments: [ @security.context, @pgq_config_bundle.db_manager, @router ]

      pgq_config_bundle.db_manager:
          class: PgqManager\ConfigBundle\Service\DatabaseManager

      pgq_config_bundle.switch_db:
          class: PgqManager\ConfigBundle\Service\SwitchDatabaseConnection
          arguments: [ @pgq_config_bundle.db_manager, @doctrine.dbal.connection_factory ]

      pgq_config_bundle.dbal_validator:
          class: PgqManager\ConfigBundle\Validator\DBALValidator
          arguments: [ @doctrine.dbal.connection_factory ]
          tags:
              - { name: validator.constraint_validator, alias: DBALConnection }