# Copyright (c) 2014 HiMedia Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @copyright 2014 HiMedia Group
# @author Karl MARQUES <kmarques@hi-media.com>
# @license Apache License, Version 2.0

parameters:
    daps_ldap.ldap.admin.dn: cn=ldap-infos,ou=users,dc=hi-media,dc=com
    daps_ldap.ldap.admin.password: 8abkutKS
    daps_ldap.ldap.admin.enable: false
    daps_ldap.ldap.srv: False # or example.com to use srv records
    daps_ldap.ldap.host: ldap://annuaire.hi-media-techno.com
    daps_ldap.ldap.port: 389
    daps_ldap.ldap.dn: uid
    daps_ldap.ldap.username_suffix: ou=users,dc=hi-media,dc=com