parameters:
#    pgqmanager.authentication.example.class: PgqManager\AuthenticationBundle\Example
    daps_ldap.ldap.admin.dn: cn=ldap-infos,ou=users,dc=hi-media,dc=com
    daps_ldap.ldap.admin.password: 8abkutKS
    daps_ldap.ldap.admin.enable: false
    daps_ldap.ldap.srv: False # or example.com to use srv records
    daps_ldap.ldap.host: ldap://annuaire.hi-media-techno.com
    daps_ldap.ldap.port: 389
    daps_ldap.ldap.dn: uid
    daps_ldap.ldap.username_suffix: ou=users,dc=hi-media,dc=com