_login:
  pattern:  /login
  defaults: { _controller: DapsLdapBundle:Secured:login }

_logout:
  pattern:  /logout

_security_check:
  pattern:  /login_check
  defaults: { _controller: DapsLdapBundle:Secured:securityCheck }