parameters:
#    main.example.class: PgqManager\MainBundle\Example

services:
#    main.example:
#        class: %main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    main.twig.globalExtension:
        class: PgqManager\MainBundle\Twig\Extension\GlobalExtension
        arguments: [@doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: twig.extension }
